# Generated by Django 6.0.4 on 2026-04-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
    ]
